imagersite/imager_api/urls.py
"""Imager api urls."""
from django.conf.urls import url

from imager_api import views


urlpatterns = [
    url(r'^photos/$', views.ApiPhotoView.as_view()),
]

imagersite/imager_images/urls.py
"""Urls for imager images."""
from django.conf.urls import url
from django.urls import reverse_lazy

from imager_images import views
from imager_images.views import (
    AlbumCreate,
    AlbumPhotoView,
    AlbumUpdate,
    AlbumView,
    PhotoCreate,
    PhotoListView,
    PhotoUpdate,
    PublicLibrary)


app_name = 'imager_images'

urlpatterns = [
    url(r'^photos/add/$', PhotoCreate.as_view(success_url="../../../images/library"),
        name='photoupload'),
    url(r'^photos/(?P<pk>\d+)/edit',
        PhotoUpdate.as_view(success_url="images/library"), name='photoedit'),
    url(r'^album/(?P<pk>\d+)/edit/$',
        AlbumUpdate.as_view(success_url="../../library"),
        name='albumedit'),
    url(r'^album/add/$', AlbumCreate.as_view(success_url="../../images/library"),
        name='albumupload'),
    url(r'^album/$', AlbumView.as_view(), name='album'),
    url(r'^album/(?P<pk>\d+)/$', AlbumPhotoView.as_view(), name='albumphoto'),
    url(r'^photos/$', PhotoListView.as_view(), name='photo'),
    url(r'^library$', views.library_view, name='library'),
    url(r'^library/(?P<user>\w+)/$', PublicLibrary.as_view(),
        name='public_library'),
]

imagersite/imager_profile/urls.py
"""Urls for profile views."""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from imager_profile import views

app_name = 'imager_profile'
urlpatterns = [
    url(r'^edit/user/$', views.UserUpdate.as_view(success_url="/profile"),
        name='userupdate'),
    url(r'^edit/$', views.ProfileUpdate.as_view(success_url="/profile"),
        name='profileupdate'),
    url(r'^$', views.profile_view, name='user_profile'),
    url(r'^(?P<username>\w+)/$', views.profile_view, name='profile'),
]

imagersite/imagersite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from imagersite import views

app_name = "imagersite"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_view, name='homepage'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^images/', include('imager_images.urls')),
    url(r'^profile/', include('imager_profile.urls')),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^api/v1/', include('imager_api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imagersite/imagersite/forms.py
from imager_profile.models import ImagerProfile


class ImagerUserForm(RegistrationForm):
    Class Meta:
        model = ImagerProfile

imagersite/imagersite/views.py
from django.shortcuts import render


def home_view(request):
    """Home view callable, for the home page."""
    return render(request, 'imagersite/home.html')

imagersite/imagersite/templates/imagersite/base.html
    {% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Imager</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap-grid.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap-reboot.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static '/css/agency.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top"></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          {% block nav %} {% endblock nav %}
        </div>
      </div>
    </nav>    

    {% block content %} {% endblock %}

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Imager 2017</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    {% load static %}
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/contact_me.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/jquery.easing.js' %}"></script>
    <script src="{% static '/js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/agency.min.js' %}"></script>
  </body>

</html>

imagersite/imagersite/templates/imagersite/home.html
{% extends 'imagersite/base.html' %}


  {% block nav %} {% include "imagersite/nav.html" %} {% endblock nav %}


{% block content %}

    <header class="masthead">
      <div class="container">
        <div class="intro-text">
          <div class="intro-lead-in">Welcome To ImagerSite!</div>
          <div class="intro-heading">
            {% if request.user.is_authenticated %}
                <h1>Hello, {{ request.user.username }}</h1>
            {% endif %}</div>
          {% if request.user.is_authenticated %}
          <a class="btn btn-xl js-scroll-trigger" href="/accounts/logout">Logout</a>
          {% else %}
          <a class="btn btn-xl js-scroll-trigger" href="/accounts/login">Login</a>
          <a class="btn btn-xl js-scroll-trigger" href="/accounts/register">Register</a>
          {% endif %}</div>
        </div>
    </header>

{% endblock %}

imagersite/imagersite/templates/imagersite/nav.html
          <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'imager_profile:user_profile' %}" style="color: gray">{{ request.user.username }}</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'homepage' %}" style="color: gray">Home</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'imager_images:library' %}" style="color: gray">Library</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'imager_images:album' %}" style="color: gray">Albums</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'imager_images:photo' %}" style="color: gray">Photos</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/accounts/logout" style="color: gray">Logout</a>
            </li>
            {% endif %}
          </ul>