imagersite/imager_api/urls.py
"""Imager api urls."""
from django.conf.urls import url

from imager_api import views


urlpatterns = [
    url(r'^photos/$', views.ApiPhotoView.as_view()),
]

imagersite/imager_images/urls.py
"""Urls for imager images."""
from django.conf.urls import url
from django.urls import reverse_lazy

from imager_images import views
from imager_images.views import (
    AlbumCreate,
    AlbumPhotoView,
    AlbumUpdate,
    AlbumView,
    PhotoCreate,
    PhotoListView,
    PhotoUpdate,
    PublicLibrary)


app_name = 'imager_images'

urlpatterns = [
    url(r'^photos/add/$', PhotoCreate.as_view(success_url="../../../images/library"),
        name='photoupload'),
    url(r'^photos/(?P<pk>\d+)/edit',
        PhotoUpdate.as_view(success_url="images/library"), name='photoedit'),
    url(r'^album/(?P<pk>\d+)/edit/$',
        AlbumUpdate.as_view(success_url="../../library"),
        name='albumedit'),
    url(r'^album/add/$', AlbumCreate.as_view(success_url="../../images/library"),
        name='albumupload'),
    url(r'^album/$', AlbumView.as_view(), name='album'),
    url(r'^album/(?P<pk>\d+)/$', AlbumPhotoView.as_view(), name='albumphoto'),
    url(r'^photos/$', PhotoListView.as_view(), name='photo'),
    url(r'^library$', views.library_view, name='library'),
    url(r'^library/(?P<user>\w+)/$', PublicLibrary.as_view(),
        name='public_library'),
]

imagersite/imager_profile/urls.py
"""Urls for profile views."""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from imager_profile import views

app_name = 'imager_profile'
urlpatterns = [
    url(r'^edit/user/$', views.UserUpdate.as_view(success_url="/profile"),
        name='userupdate'),
    url(r'^edit/$', views.ProfileUpdate.as_view(success_url="/profile"),
        name='profileupdate'),
    url(r'^$', views.profile_view, name='user_profile'),
    url(r'^(?P<username>\w+)/$', views.profile_view, name='profile'),
]

imagersite/imagersite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from imagersite import views

app_name = "imagersite"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_view, name='homepage'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^images/', include('imager_images.urls')),
    url(r'^profile/', include('imager_profile.urls')),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^api/v1/', include('imager_api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imagersite/imager_profile/models.py
"""Models for imagersite."""
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from multiselectfield import MultiSelectField


class ProfileManager(models.Manager):
    """Redefine profile manager settings."""

    def get_queryset(self):
        """Redefine get_queryset is_active."""
        return super().get_queryset().filter(user__is_active=True)


class ImagerProfile(models.Model):
    """Create a new imager profile."""

    user = models.OneToOneField(
        User,
        related_name='profile',
        on_delete=models.CASCADE)

    objects = models.Manager()
    active = ProfileManager()
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=12, blank=True)
    website = models.URLField(blank=True)
    location = models.CharField(max_length=30, blank=True)
    fee = models.DecimalField(decimal_places=2, max_digits=6,
                              blank=True, null=True)
    CAMERAS = [
        ('CANON', 'Canon'),
        ('NIKON', 'Nikon'),
        ('SONY', 'Sony'),
        ('FUJIFILM', 'Fujifilm')
    ]
    camera = MultiSelectField(
        max_choices=1,
        choices=CAMERAS,
        blank=True
    )
    SERVICES = [
        ('WEDDINGS', 'Weddings'),
        ('SCHOOL', 'School'),
        ('FAMILY', 'Family'),
        ('BABIES', 'Babies'),
        ('NATURE', 'Nature'),
        ('ABSTACT', 'Abstract'),
        ('OTHER', 'Other')
    ]
    services = MultiSelectField(
        max_choices=7,
        choices=SERVICES,
        blank=True
    )
    bio = models.TextField(blank=True)
    PHOTO_STYLES = [
        ('BW', 'Black and white'),
        ('COLOR', 'Color'),
        ('STILL', 'Still'),
        ('ACTION', 'Action'),
    ]
    photo_styles = MultiSelectField(
        max_choices=4,
        choices=PHOTO_STYLES,
        blank=True
    )

    # class Meta:
    #     """Set permissions on model."""

    #     permissions = (
    #         ("view_imagerprofile", "Can see books"),
    #         ("view_albums", "Can see books"),
    #         ("view_images", "Can see books"),
    #     )

    @property
    def is_active(self):
        """Create property is_active for model."""
        return self.user.is_active

    def __repr__(self):
        """Make me a string."""
        return self.user.username

    def __str__(self):
        """Render name as string."""
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    """Automatically create profile when user is created."""
    if kwargs['created']:
        profile = ImagerProfile(user=kwargs['instance'])
        profile.save()

imagersite/imager_profile/views.py
"""Views for imager profile."""
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic.edit import UpdateView

from imager_images.models import Photo

from imager_profile.models import ImagerProfile


@login_required(login_url='/accounts/login/')
def profile_view(request, username=None):
    """Request for profile view."""
    if username is None and request.user.is_authenticated:
        request_user = User.objects.filter(username=request.user)
        profile = ImagerProfile.objects.get(user=request_user)
        image_query = Photo.objects.filter(user=profile)
        image_count = image_query.count()
        return render(request, 'imager_profile/profiles.html',
                               context={'profile': profile,
                                        'image_count': image_count})
    else:
        request_user = User.objects.filter(username=username)
        profile = ImagerProfile.objects.get(user=request_user)
        return render(request, 'imager_profile/profiles.html',
                               context={'profile': profile})


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    """Class based to view to generate for user to update profile."""

    model = ImagerProfile
    fields = [
        'first_name',
        'last_name',
        'phone',
        'website',
        'location',
        'fee',
        'camera',
        'services',
        'bio',
        'photo_styles']
    template_name_suffix = '_update_form'
    context_object_name = 'profile'
    redirect_field_name = '/accounts/login'

    def get_object(self):
        """Populate form."""
        return self.request.user.profile


class UserUpdate(LoginRequiredMixin, UpdateView):
    """Update user information view."""

    model = User
    fields = [
        'first_name',
        'last_name',
        'email',
    ]
    template_name = 'imager_profile/user_update_form.html'
    context_object_name = 'user'
    redirect_field_name = '/accounts/login'

    def get_object(self):
        """Fill form data."""
        return self.request.user

imagersite/imager_profile/templates/imager_profile/imagerprofile_update_form.html
{% extends 'imagersite/base.html' %}

{% block nav %} {% include "imagersite/nav.html" %} {% endblock nav %}

{% block content %}

{% load static %}

<div class='imager_forms' >
<form action="" method="post" style="margin-top: 100px;">{% csrf_token %}
        <div class="row">
            <div class="col-sm-4">
                <div class="team-member">
                    {{ form.first_name.label_tag }} 
                    {{ form.first_name }}

                    {{ form.last_name.label_tag }}
                    {{ form.last_name }}

                    {{ form.phone.label_tag }}
                    {{ form.phone }}

                    {{ form.website.label_tag }}
                    {{ form.website }}

                    {{ form.location.label_tag }}
                    {{ form.location }}

                    {{ form.fee.label_tag }}
                    {{ form.fee }}
                </div>
            </div>
            <div class="col-sm-4">
                <div class="team-member">
                    

                    {{ form.services.label_tag }}
                    {{ form.services }}
                </div>
            </div>
            <div class="col-sm-4">
                <div class="team-member">
                    {{ form.camera.label_tag }}
                    {{ form.camera }}

                    {{ form.photo_styles.label_tag }}
                    {{ form.photo_styles }}
                </div>
            </div>
        </div>

            {{ form.bio.label_tag }}
            {{ form.bio }}

    <input type="submit" value="Update" />
</form>
</div>

{% endblock %}

imagersite/imager_profile/templates/imager_profile/profile_update_form.html
{% extends 'imagersite/base.html' %}

{% block nav %} {% include "imager_images/nav.html" %} {% endblock nav %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form }}
    <input type="submit" value="Update" />
</form>
{% endblock %}

imagersite/imager_profile/templates/imager_profile/profiles.html
{% extends 'imagersite/base.html' %}

 {% block nav %} {% include "imagersite/nav.html" %} {% endblock nav %}

{% block content %}


    <header class="masthead">
      <div class="container">
        <div class="intro-text">
          <div class="intro-heading">
            <h1>{{ profile.first_name }} {{ profile.last_name }}</h1>
          </div>       
          <p>{{ profile.bio }}</p>
          <a href="{% url 'imager_images:public_library' user=profile.user %}"><button id="sendMessageButton" class="btn btn-xl" type="submit">See My Photos</button></a>
        </div>
      </div>
    </header>
    <!-- Portfolio Grid -->
    <!-- Stats -->
    <section class="bg-light" id="team">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <ul class="list-inline social-buttons">
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-twitter"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-facebook"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-linkedin"></i>
                  </a>
                </li>
              </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <div class="team-member">
                {% load static %}
              <h4>Personal Information</h4>
              <p class="text-muted"><strong>FULL NAME: </strong>{{ profile.first_name }} {{ profile.last_name }}</p>
              <p class="text-muted"><strong>USERNAME: </strong>{{ profile.user }}</p>
              <p class="text-muted"><strong>STANDARD FEE: </strong>{{ profile.fee }}</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
                {% load static %}
              <h4>Contact</h4>
              <p class="text-muted"><strong>PHONE: </strong>{{ profile.phone }}</p>
              <p class="text-muted"><strong>WEBSITE: </strong>{{ profile.website }}</p>
              <p class="text-muted"><strong>LOCATION: </strong>{{ profile.location }}</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
                {% load static %}
              <h4>WORK</h4>
              <p class="text-muted"><strong>SERVICES: </strong>{{ profile.services }}</p>
              <p class="text-muted"><strong>STYLES: </strong>{{ profile.photo_styles }}</p>
              <p class="text-muted"><strong>CAMERA: </strong>{{ profile.camera }}</p>
            </div>
          </div>
        </div>
        {% if request.user.username == profile.user.username %}
        <h3 style='text-align: center;'>Account Information</h2>
        <div class="row">
          <div class="col-sm-4">
            <div class="team-member">
                {% load static %}
              <h4>Total Uploads</h4>
              <p class="text-muted"><strong>PHOTOS: </strong>{{ image_count }}</p>
              <p class="text-muted"><strong>ALBUMS: </strong>###</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
                {% load static %}
              <h4>Edit</h4>
              <p class="text-muted"><strong><a href="{% url 'imager_profile:profileupdate' %}">UPDATE PROFILE</a></strong></p>
              <p class="text-muted"><strong><a href="{% url 'imager_profile:userupdate' %}">UPDATE USER ACCOUNT</a></strong></p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
                {% load static %}
              <h4>Upload</h4>
              <p class="text-muted"><strong><a href="{% url 'imager_images:photoupload' %}">UPLOAD PHOTOS</a></strong></p>
              <p class="text-muted"><strong><a href="{% url 'imager_images:albumupload' %}">CREATE ALBUM</a></strong></p>
            </div>
          </div>
        </div>
    {% endif %}
        </div>
      </div>
    </section>

{% endblock %}

imagersite/imager_profile/templates/imager_profile/user_update_form.html
{% extends 'imagersite/base.html' %}

{% block nav %} {% include "imagersite/nav.html" %} {% endblock nav %}

{% block content %}

{% load static %}

<div class='imager_forms'>
<form action="" method="post" style="margin-top: 100px;">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Update" />
</form>
</div>

{% endblock %}